######################## GNU General Public License 3.0 ########################
##                                                                            ##
## Copyright (C) 2022─2023 Kevin Matthes                                      ##
##                                                                            ##
## This program is free software: you can redistribute it and/or modify       ##
## it under the terms of the GNU General Public License as published by       ##
## the Free Software Foundation, either version 3 of the License, or          ##
## (at your option) any later version.                                        ##
##                                                                            ##
## This program is distributed in the hope that it will be useful,            ##
## but WITHOUT ANY WARRANTY; without even the implied warranty of             ##
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              ##
## GNU General Public License for more details.                               ##
##                                                                            ##
## You should have received a copy of the GNU General Public License          ##
## along with this program.  If not, see <https://www.gnu.org/licenses/>.     ##
##                                                                            ##
################################################################################

################################################################################
##
##  AUTHOR      Kevin Matthes
##  BRIEF       Set the release date of the CITATION.cff to the present day.
##  COPYRIGHT   GPL-3.0
##  DATE        2022─2023
##  FILE        action.yml
##  NOTE        See `LICENSE' for full license.
##              See `README.md' for project details.
##
################################################################################

# The icon with which this Action is presented in the Marketplace.
branding:
  color: green
  icon: sunrise

# About this Action.
author: 'https://github.com/kevinmatthes'
description: Set the release date of the CITATION.cff to the present day.
name: cff-release-today

# The information to be input.
inputs:
  commit:
    default: false
    description: Whether to commit the changes.
    required: false
  checkout:
    default: false
    description: Whether to checkout the repository to work on.
    required: false
  push:
    default: false
    description: Whether to push the committed changes.
    required: false
  validate:
    default: true
    description: Whether to validate the CITATION.cff before updating it.
    required: false

# The actual behaviour of this Action.
runs:
  using: composite
  steps:
    - name: Validate the input `checkout`.
      uses: kevinmatthes/validate-boolean@v0.1.2
      with:
        check: ${{ inputs.checkout }}

    - name: Validate the input `commit`.
      uses: kevinmatthes/validate-boolean@v0.1.2
      with:
        check: ${{ inputs.commit }}

    - name: Validate the input `push`.
      uses: kevinmatthes/validate-boolean@v0.1.2
      with:
        check: ${{ inputs.push }}

    - name: Validate the input `validate`.
      uses: kevinmatthes/validate-boolean@v0.1.2
      with:
        check: ${{ inputs.validate }}

    - if: inputs.checkout == 'true' || inputs.push == 'true'
      name: Checkout the repository to work on.
      uses: actions/checkout@v4.1.3
      with:
        persist-credentials: ${{ inputs.push }}

    - if: inputs.validate == 'true'
      name: Validate the CITATION.cff before updating it.
      uses: citation-file-format/cffconvert-github-action@2.0.0
      with:
        args: --validate

    - if: inputs.commit == 'true' || inputs.push == 'true'
      name: Configure the Git identity.
      uses: fregante/setup-git-user@v2.0.1

    - name: Update the release date.
      run: |
        sed 's/^date-released: ....-..-../date-released: '`date +%F`'/g' \
            CITATION.cff >> CITATION.cff.tmp \
        && mv CITATION.cff.tmp CITATION.cff
      shell: bash

    - if: inputs.commit == 'true' || inputs.push == 'true'
      name: Commit the changes.
      run: |
        git add CITATION.cff \
        && git commit --allow-empty -m \
               "`git config --list \
                 | grep user\.name \
                 | cut -d= -f2`:  Update CFF release date"
      shell: bash

    - if: inputs.push == 'true'
      name: Push the changes.
      run: git push
      shell: bash

################################################################################
