######################## GNU General Public License 3.0 ########################
##                                                                            ##
## Copyright (C) 2022 Kevin Matthes                                           ##
##                                                                            ##
## This program is free software: you can redistribute it and/or modify       ##
## it under the terms of the GNU General Public License as published by       ##
## the Free Software Foundation, either version 3 of the License, or          ##
## (at your option) any later version.                                        ##
##                                                                            ##
## This program is distributed in the hope that it will be useful,            ##
## but WITHOUT ANY WARRANTY; without even the implied warranty of             ##
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              ##
## GNU General Public License for more details.                               ##
##                                                                            ##
## You should have received a copy of the GNU General Public License          ##
## along with this program.  If not, see <https://www.gnu.org/licenses/>.     ##
##                                                                            ##
################################################################################

################################################################################
##
##  AUTHOR      Kevin Matthes
##  BRIEF       Set the release date of the CITATION.cff to the present day.
##  COPYRIGHT   GPL-3.0
##  DATE        2022
##  FILE        action.yml
##  NOTE        See `LICENSE' for full license.
##              See `README.md' for project details.
##
################################################################################

# The icon with which this Action is presented in the Marketplace.
branding:
  color: green
  icon: sunrise

# About this Action.
author: 'https://github.com/kevinmatthes'
description: Set the release date of the CITATION.cff to the present day.
name: cff-release-today

# The actual behaviour of this Action.
runs:
  using: composite
  steps:
    - name: Update the release date and save it in a new file.
      run: |
        sed \
            's/^date-released: ....-..-../date-released: '`date +%F`'/g' \
            CITATION.cff >> CITATION.cff.tmp

    - name: Write back the update to the original file.
      run: mv CITATION.cff.tmp CITATION.cff

################################################################################
